//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClientForUnregUsers.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmitResult", Namespace="http://schemas.datacontract.org/2004/07/SchoolLibrary.Services.UnregisteredUserMa" +
        "nagment")]
    [System.SerializableAttribute()]
    public partial class SubmitResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUnregisteredUserService")]
    public interface IUnregisteredUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnregisteredUserService/GetAllUsers", ReplyAction="http://tempuri.org/IUnregisteredUserService/GetAllUsersResponse")]
        SchoolLibrary.BusinessModels.Models.UserProfileBusinessModel[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnregisteredUserService/GetAllUsers", ReplyAction="http://tempuri.org/IUnregisteredUserService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<SchoolLibrary.BusinessModels.Models.UserProfileBusinessModel[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnregisteredUserService/Submit", ReplyAction="http://tempuri.org/IUnregisteredUserService/SubmitResponse")]
        global::AdminClientForUnregUsers.ServiceReference1.SubmitResult Submit(int userId, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnregisteredUserService/Submit", ReplyAction="http://tempuri.org/IUnregisteredUserService/SubmitResponse")]
        System.Threading.Tasks.Task<global::AdminClientForUnregUsers.ServiceReference1.SubmitResult> SubmitAsync(int userId, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnregisteredUserService/GetAllRoles", ReplyAction="http://tempuri.org/IUnregisteredUserService/GetAllRolesResponse")]
        string[] GetAllRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnregisteredUserService/GetAllRoles", ReplyAction="http://tempuri.org/IUnregisteredUserService/GetAllRolesResponse")]
        System.Threading.Tasks.Task<string[]> GetAllRolesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUnregisteredUserServiceChannel : global::AdminClientForUnregUsers.ServiceReference1.IUnregisteredUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnregisteredUserServiceClient : System.ServiceModel.ClientBase<global::AdminClientForUnregUsers.ServiceReference1.IUnregisteredUserService>, global::AdminClientForUnregUsers.ServiceReference1.IUnregisteredUserService {
        
        public UnregisteredUserServiceClient() {
        }
        
        public UnregisteredUserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UnregisteredUserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnregisteredUserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnregisteredUserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SchoolLibrary.BusinessModels.Models.UserProfileBusinessModel[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<SchoolLibrary.BusinessModels.Models.UserProfileBusinessModel[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public global::AdminClientForUnregUsers.ServiceReference1.SubmitResult Submit(int userId, string role) {
            return base.Channel.Submit(userId, role);
        }
        
        public System.Threading.Tasks.Task<global::AdminClientForUnregUsers.ServiceReference1.SubmitResult> SubmitAsync(int userId, string role) {
            return base.Channel.SubmitAsync(userId, role);
        }
        
        public string[] GetAllRoles() {
            return base.Channel.GetAllRoles();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllRolesAsync() {
            return base.Channel.GetAllRolesAsync();
        }
    }
}
