// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace SchoolLibrary.DataAccess.Migrations
{
    public sealed partial class Test4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Test4));
        
        string IMigrationMetadata.Id
        {
            get { return "201310082312365_Test4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return this.Resources.GetString("Target"); }
        }
    }
}
